# Extract parish ministries

Load the parish list generated by `01_build_parish_list.ipynb` as the starting point for ministry extraction. Run this notebook from the project root.

## Environment setup
Install project dependencies with `%pip install -e .` if needed. Set `OPENAI_API_KEY=your-key-here` in the project-root `.env` file, replacing the placeholder with your key. `.env.example` documents the setting; `.env` is ignored by Git.

Load the settings into the notebook process without overriding existing environment variables. Page downloading does not require an API key.

Set `HTML_CACHE_DIR` in `.env` to choose the HTML cache folder. An existing environment variable takes precedence. Individual scraping functions also accept a `cache_dir` override. Existing cache files are not moved automatically.

In [4]:
from dotenv import load_dotenv

_ = load_dotenv(".env", override=False)

In [5]:
from pathlib import Path

import pandas as pd

input_path = Path("data/01_parish_list/parish_list.csv")
parishes_df = pd.read_csv(input_path)

print(f"Loaded {len(parishes_df)} parishes from {input_path}")
parishes_df.head()

Loaded 784 parishes from data\01_parish_list\parish_list.csv

,name,address,site_url,diocese,category,parish_list_url
0,Father Purcell Memorial Center for Exceptional...,"Montgomery, AL",https://fatherpurcell.org/,Archdiocese of Mobile,Sunday Mass Schedule,https://mobarch.org/parishfinder
1,Holy Spirit Catholic Parish,"Montgomery, AL",https://holyspiritmgm.org/,Archdiocese of Mobile,Sunday Mass Schedule,https://mobarch.org/parishfinder
2,Blessed Francis Xavier Seelos Parish,"31122 US Hwy 31, Spanish Fort, AL, 36527",https://francisxseelos.org/,Archdiocese of Mobile,Baldwin/Escambia Deanery,https://mobarch.org/parishfinder
3,Chapel of Our Lady of Bon Secour,"17266 County Road 49 South, Bon Secour, AL, 36511",https://www.stjohnms.com/our-lady-of-bon-secour,Archdiocese of Mobile,Baldwin/Escambia Deanery,https://mobarch.org/parishfinder
4,Christ the King Catholic Church,"711 College Avenue, Daphne, AL, 36526",https://ctkdaphne.org/,Archdiocese of Mobile,Baldwin/Escambia Deanery,https://mobarch.org/parishfinder

## Discover parish site pages
For the first `PARISH_LIMIT` rows, check `/sitemap.xml` and sitemap declarations in `/robots.txt`, follow sitemap indexes, and also collect homepage/navigation links. Keep same-site HTTP(S) page URLs, remove fragments, exclude common file downloads, and deduplicate per parish. Query strings and distinct paths are preserved.

Downloads are cached in the folder selected by `HTML_CACHE_DIR` in `.env` (or the environment). Failures are recorded in `discovery_errors_df` so homepage discovery can still work when a sitemap is unavailable. This step discovers URLs; it does not download every discovered page.

In [7]:
from utils.scraping import get_cache_dir
from utils.page_discovery import discover_site_pages

PARISH_LIMIT = 10
output_dir = Path("data/02_extract_ministries")
cache_dir = get_cache_dir()
selected_parishes = parishes_df.head(PARISH_LIMIT)
page_rows = []
error_rows = []

for parish_index, parish in selected_parishes.iterrows():
    site_url = parish["site_url"] if pd.notna(parish["site_url"]) else ""
    pages, errors = discover_site_pages(site_url, cache_dir)
    parish_info = {
        "parish_index": parish_index,
        "name": parish["name"],
        "diocese": parish["diocese"],
        "site_url": site_url,
    }
    page_rows.extend({**parish_info, **page} for page in pages)
    error_rows.extend({**parish_info, **error} for error in errors)
    print(f"{parish['name']}: {len(pages)} pages, {len(errors)} discovery issues")

parish_columns = ["parish_index", "name", "diocese", "site_url"]
site_pages_df = pd.DataFrame(page_rows, columns=parish_columns + ["page_url", "sources"])
discovery_errors_df = pd.DataFrame(error_rows, columns=parish_columns + ["url", "error"])
output_dir.mkdir(parents=True, exist_ok=True)
site_pages_df.to_csv(output_dir / "site_pages.csv", index=False)
discovery_errors_df.to_csv(output_dir / "discovery_errors.csv", index=False)
site_pages_df.head(20)

Father Purcell Memorial Center for Exceptional Children: 11 pages, 0 discovery issues
Holy Spirit Catholic Parish: 52 pages, 0 discovery issues
Blessed Francis Xavier Seelos Parish: 479 pages, 0 discovery issues
Chapel of Our Lady of Bon Secour: 264 pages, 1 discovery issues
Christ the King Catholic Church: 859 pages, 0 discovery issues
Our Lady of the Gulf Catholic Church: 237 pages, 0 discovery issues
Shrine of the Holy Cross & St. John Mission: 46 pages, 0 discovery issues
St Robert Bellarmine Catholic Church: 112 pages, 0 discovery issues
St. Agatha Parish: 38 pages, 0 discovery issues
St. Bartholomew: 29 pages, 0 discovery issues

,parish_index,name,diocese,site_url,page_url,sources
0,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/,"homepage, homepage_link, sitemap"
1,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/admission,"homepage_link, sitemap"
2,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/blog,sitemap
3,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/bulletins,sitemap
4,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/calendar,sitemap
5,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/contact,"homepage_link, sitemap"
6,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/events,sitemap
7,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/history,"homepage_link, sitemap"
8,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/news,sitemap
9,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/photoalbums,sitemap
10,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/services,"homepage_link, sitemap"
11,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/,"homepage, homepage_link, sitemap"
12,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/adults,"homepage_link, sitemap"
13,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/become-catholic-join...,"homepage_link, sitemap"
14,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/blog,sitemap
15,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/boy-scouts,"homepage_link, sitemap"
16,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/bulletins,"homepage_link, sitemap"
17,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/calendar,sitemap
18,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/catholic-resources,"homepage_link, sitemap"
19,1,Holy Spirit Catholic Parish,Archdiocese of Mobile,https://holyspiritmgm.org/,https://holyspiritmgm.org/cdn-cgi/l/email-prot...,homepage_link

In [8]:
# Inspect unavailable sitemaps or other requests that need attention.
discovery_errors_df

,parish_index,name,diocese,site_url,url,error
0,3,Chapel of Our Lady of Bon Secour,Archdiocese of Mobile,https://www.stjohnms.com/our-lady-of-bon-secour,https://www.stjohnms.com/our-lady-of-bon-secour,404 Client Error: Not Found for url: https://s...

## Fetch page titles and clean text
Process every page in the saved `site_pages.csv` (the parishes selected during discovery). This section can run independently after discovery has been saved. Reuse cached HTML in the folder selected by `HTML_CACHE_DIR` and cache any new successful downloads without changing existing raw files.

Save `page_content.json` as a JSON array of page records with the original discovery columns plus `final_url` (after redirects), `page_title`, and `clean_text`. Clean text removes markup, scripts, styles, embedded media, and explicitly hidden elements, and normalizes whitespace. Visible navigation is retained because it can identify ministries. JavaScript is not executed. Missing titles remain empty.

Failed pages are saved to `page_content_errors.json` for inspection and retry on the next run; successful pages are loaded from the HTML cache on reruns.

In [9]:
from utils.scraping import get_cache_dir
from pathlib import Path

import pandas as pd
import requests

from utils.page_content import extract_page_content

output_dir = Path("data/02_extract_ministries")
cache_dir = get_cache_dir()
site_pages_df = pd.read_csv(output_dir / "site_pages.csv", keep_default_na=False)
content_rows = []
content_error_rows = []

for parish_index, parish_pages in site_pages_df.groupby("parish_index", sort=False):
    successful_pages = 0
    for page in parish_pages.to_dict("records"):
        try:
            content = extract_page_content(page["page_url"], cache_dir)
        except (requests.RequestException, OSError, ValueError) as exc:
            content_error_rows.append({**page, "error": str(exc)})
            continue
        content_rows.append({**page, **content})
        successful_pages += 1
    print(f"{parish_pages.iloc[0]['name']}: {successful_pages}/{len(parish_pages)} pages extracted")

page_content_df = pd.DataFrame(
    content_rows,
    columns=list(site_pages_df.columns) + ["final_url", "page_title", "clean_text"],
)
page_content_errors_df = pd.DataFrame(
    content_error_rows, columns=list(site_pages_df.columns) + ["error"],
)
page_content_df.to_json(
    output_dir / "page_content.json", orient="records", indent=2, force_ascii=False,
)
page_content_errors_df.to_json(
    output_dir / "page_content_errors.json", orient="records", indent=2, force_ascii=False,
)
print(f"Saved {len(page_content_df)} pages and {len(page_content_errors_df)} errors to {output_dir}")
page_content_df.head()

Father Purcell Memorial Center for Exceptional Children: 11/11 pages extracted
Holy Spirit Catholic Parish: 51/52 pages extracted
Blessed Francis Xavier Seelos Parish: 478/479 pages extracted
Chapel of Our Lady of Bon Secour: 264/264 pages extracted

c:\Users\joema\anaconda3\Lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Christ the King Catholic Church: 858/859 pages extracted
Our Lady of the Gulf Catholic Church: 235/237 pages extracted
Shrine of the Holy Cross & St. John Mission: 45/46 pages extracted
St Robert Bellarmine Catholic Church: 111/112 pages extracted
St. Agatha Parish: 38/38 pages extracted
St. Bartholomew: 28/29 pages extracted
Saved 2119 pages and 8 errors to data\02_extract_ministries

,parish_index,name,diocese,site_url,page_url,sources,final_url,page_title,clean_text
0,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/,"homepage, homepage_link, sitemap",https://fatherpurcell.org/,Father Purcell Memorial Center for Exceptional...,Home Our History Services Admission Contact Us...
1,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/admission,"homepage_link, sitemap",https://fatherpurcell.org/admission,Father Purcell Memorial Center for Exceptional...,Home Our History Services Admission Contact Us...
2,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/blog,sitemap,https://fatherpurcell.org/blog,News,Home Our History Services Admission Contact Us...
3,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/bulletins,sitemap,https://fatherpurcell.org/bulletins,Bulletin,Home Our History Services Admission Contact Us...
4,0,Father Purcell Memorial Center for Exceptional...,Archdiocese of Mobile,https://fatherpurcell.org/,https://fatherpurcell.org/calendar,sitemap,https://fatherpurcell.org/calendar,Calendar,Home Our History Services Admission Contact Us...

In [ ]:
# Inspect pages that could not be downloaded or parsed.
page_content_errors_df